export const navItems = [
  {
    id: 0,
    url: '/',
    text: 'Home',
  },
  {
    id: 1,
    url: './Components/About',
    text: 'About',
  },
  {
    id: 2,
    url: './Components/Services',
    text: 'Services',
  },
  {
    id: 3,
    url: '/',
    text: 'Skills',
  },
  {
    id: 4,
    url: '/',
    text: 'Projects',
  },
  {
    id: 5,
    url: '/',
    text: 'Contact',
  },
];

export const projects = [
  {
    id: 1,
    image: '/images/card-images/1.png',
    title: 'DocRay',
    desc: 'Pneumonia and TB detection System',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
      mongodb: '/images/card-icons/mongodb.png',
      express: '/images/card-icons/express.png',
      node: '/images/card-icons/node.png',
    },
    url: 'https://github.com/UsamaGhazan/DOCRAY',
  },
  {
    id: 2,
    image: '/images/card-images/17.png',
    title: 'Progressive Internationals',
    desc: 'Petrol Pump Management Sytem',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
      mongodb: '/images/card-icons/mongodb.png',
      express: '/images/card-icons/express.png',
      node: '/images/card-icons/node.png',
    },
    url: 'https://github.com/UsamaGhazan/Petrol-Pump-Management-System',
  },
  {
    id: 3,
    image: '/images/card-images/16.png',
    title: 'Ecommerce Website',
    desc: 'Fully functional ecommerce website',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      mongodb: '/images/card-icons/mongodb.png',
      express: '/images/card-icons/express.png',
      react: '/images/card-icons/react.png',
      node: '/images/card-icons/node.png',
    },
    url: 'https://github.com/UsamaGhazan/MERN-Ecommerce-Website',
  },
  {
    id: 4,
    image: '/images/card-images/14.png',
    title: 'Stripe menu',
    desc: 'Stripe Website Clone',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Stripe-submenus-Mini-Project',
  },
  {
    id: 5,
    image: '/images/card-images/4.png',
    title: 'Reviews',
    desc: 'Showing customer reviews',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Reviews-mini-project',
  },
  {
    id: 6,
    image: '/images/card-images/5.png',
    title: 'Accordian',
    desc: 'Accordian using ReactJS',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Accordian-mini-project',
  },
  {
    id: 7,
    image: '/images/card-images/6.png',
    title: 'Menu',
    desc: 'Food Menu showing cast and description',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Menu-mini-project',
  },
  {
    id: 8,
    image: '/images/card-images/7.png',
    title: 'Tabs',
    desc: 'Showing experience of employees',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/tabs--mini-project',
  },
  {
    id: 9,
    image: '/images/card-images/8.png',
    title: 'Slider',
    desc: 'Showing reviews using slider functionality',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Slider-mini-project',
  },
  {
    id: 10,
    image: '/images/card-images/9.png',
    title: 'Lorem Ipsum',
    desc: 'ParaGraph generator',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/lorem-ipsum--mini-project',
  },
  {
    id: 11,
    image: '/images/card-images/10.png',
    title: 'Color Generator',
    desc: 'Generates different colors using filters',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/color-generator-mini-project',
  },
  {
    id: 12,
    image: '/images/card-images/11.png',
    title: 'Grocery Bud',
    desc: 'Grocery list maker',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/grocery-bud-mini-project',
  },
  {
    id: 13,
    image: '/images/card-images/12.png',
    title: 'Navbar',
    desc: 'Simple Navbar functionality',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Navbar-Mini-Project',
  },
  {
    id: 14,
    image: '/images/card-images/13.png',
    title: 'Sidebar and Modal',
    desc: 'Sidebar and Modal using ReactJS',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/SideBar-Modal-Mini-Project',
  },
  {
    id: 15,
    image: '/images/card-images/3.png',
    title: 'Tours',
    desc: 'Tour details and costs   ',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Tours-mini-project',
  },
  {
    id: 16,
    image: '/images/card-images/15.png',
    title: 'Cart',
    desc: 'Cart functionality of website',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Cart-Mini_Project',
  },
  {
    id: 17,
    image: '/images/card-images/2.png',
    title: 'Birhtday Reminder',
    desc: 'Birthday reminder using ReactJS',
    icons: {
      html: '/images/card-icons/html.png',
      css: '/images/card-icons/css.png',
      react: '/images/card-icons/react.png',
    },
    url: 'https://github.com/UsamaGhazan/Birthday-Reminder-mini-project',
  },
];
